# Generated by Django 4.0.1 on 2022-01-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_alter_user_uploaded_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
