# Generated by Django 4.0.1 on 2022-01-05 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subscribers',
            field=models.ManyToManyField(related_name='subs_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
